<a href="https://colab.research.google.com/github/Anu0034/Projects/blob/main/Randomforest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/drug200.csv')
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
df.tail()

Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [ ]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [ ]:
df.dtypes

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
Drug            object
dtype: object

In [ ]:
df.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
df1=pd.get_dummies(df[['Sex','BP','Cholesterol']],drop_first=True)
df1

Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0        0       0          0                   0
1        1       1          0                   0
2        1       1          0                   0
3        0       0          1                   0
4        0       1          0                   0
..     ...     ...        ...                 ...
195      0       1          0                   0
196      1       1          0                   0
197      1       0          1                   0
198      1       0          1                   1
199      0       1          0                   1

[200 rows x 4 columns]

In [ ]:
df2=pd.concat([df,df1],axis=1)
df2

Age Sex      BP Cholesterol  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  \
0     23   F    HIGH        HIGH   25.355  DrugY      0       0          0   
1     47   M     LOW        HIGH   13.093  drugC      1       1          0   
2     47   M     LOW        HIGH   10.114  drugC      1       1          0   
3     28   F  NORMAL        HIGH    7.798  drugX      0       0          1   
4     61   F     LOW        HIGH   18.043  DrugY      0       1          0   
..   ...  ..     ...         ...      ...    ...    ...     ...        ...   
195   56   F     LOW        HIGH   11.567  drugC      0       1          0   
196   16   M     LOW        HIGH   12.006  drugC      1       1          0   
197   52   M  NORMAL        HIGH    9.894  drugX      1       0          1   
198   23   M  NORMAL      NORMAL   14.020  drugX      1       0          1   
199   40   F     LOW      NORMAL   11.349  drugX      0       1          0   

     Cholesterol_NORMAL  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
..                  ...  
195                   0  
196                   0  
197                   0  
198                   1  
199                   1  

[200 rows x 10 columns]

In [ ]:
df2.drop(columns=['Sex','BP','Cholesterol'],inplace=True)

In [ ]:
df2

Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0     23   25.355  DrugY      0       0          0                   0
1     47   13.093  drugC      1       1          0                   0
2     47   10.114  drugC      1       1          0                   0
3     28    7.798  drugX      0       0          1                   0
4     61   18.043  DrugY      0       1          0                   0
..   ...      ...    ...    ...     ...        ...                 ...
195   56   11.567  drugC      0       1          0                   0
196   16   12.006  drugC      1       1          0                   0
197   52    9.894  drugX      1       0          1                   0
198   23   14.020  drugX      1       0          1                   1
199   40   11.349  drugX      0       1          0                   1

[200 rows x 7 columns]

In [ ]:
df2.dtypes

Age                     int64
Na_to_K               float64
Drug                   object
Sex_M                   uint8
BP_LOW                  uint8
BP_NORMAL               uint8
Cholesterol_NORMAL      uint8
dtype: object

In [ ]:
x=df2.drop(['Drug'],axis=1).values
x

array([[23.   , 25.355,  0.   ,  0.   ,  0.   ,  0.   ],
       [47.   , 13.093,  1.   ,  1.   ,  0.   ,  0.   ],
       [47.   , 10.114,  1.   ,  1.   ,  0.   ,  0.   ],
       ...,
       [52.   ,  9.894,  1.   ,  0.   ,  1.   ,  0.   ],
       [23.   , 14.02 ,  1.   ,  0.   ,  1.   ,  1.   ],
       [40.   , 11.349,  0.   ,  1.   ,  0.   ,  1.   ]])

In [ ]:
y=df2['Drug'].values
y

array(['DrugY', 'drugC', 'drugC', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'DrugY', 'drugX', 'drugA', 'drugC', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugX', 'DrugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'DrugY', 'drugB',
       'DrugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugB', 'drugC',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugA', 'DrugY',
       'drugX', 'drugB', 'DrugY', 'drugA', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'Dru

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[20.   , 11.262,  0.   ,  0.   ,  0.   ,  0.   ],
       [56.   , 25.395,  0.   ,  0.   ,  0.   ,  0.   ],
       [74.   ,  9.567,  1.   ,  0.   ,  0.   ,  0.   ],
       [43.   , 15.376,  1.   ,  1.   ,  0.   ,  0.   ],
       [46.   ,  7.285,  1.   ,  0.   ,  1.   ,  1.   ],
       [61.   , 25.475,  0.   ,  0.   ,  0.   ,  0.   ],
       [50.   , 15.79 ,  1.   ,  0.   ,  1.   ,  1.   ],
       [64.   , 20.932,  1.   ,  0.   ,  0.   ,  1.   ],
       [62.   , 16.594,  1.   ,  0.   ,  1.   ,  0.   ],
       [55.   , 10.977,  0.   ,  0.   ,  0.   ,  0.   ],
       [67.   , 10.898,  1.   ,  0.   ,  1.   ,  1.   ],
       [35.   ,  7.845,  1.   ,  0.   ,  1.   ,  1.   ],
       [43.   , 12.859,  1.   ,  0.   ,  1.   ,  1.   ],
       [58.   , 14.239,  0.   ,  0.   ,  0.   ,  1.   ],
       [32.   , 10.292,  0.   ,  0.   ,  0.   ,  1.   ],
       [65.   , 13.769,  0.   ,  1.   ,  0.   ,  1.   ],
       [31.   , 30.366,  1.   ,  0.   ,  0.   ,  0.   ],
       [69.   , 10.065,  0.   ,

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
x_train

array([[-1.59046320e+00, -6.85429715e-01, -1.08972474e+00,
        -6.43538199e-01, -6.54653671e-01, -8.91555828e-01],
       [ 6.25107426e-01,  1.36866064e+00, -1.08972474e+00,
        -6.43538199e-01, -6.54653671e-01, -8.91555828e-01],
       [ 1.73289274e+00, -9.31781032e-01,  9.17662935e-01,
        -6.43538199e-01, -6.54653671e-01, -8.91555828e-01],
       [-1.74959744e-01, -8.75009148e-02,  9.17662935e-01,
         1.55390931e+00, -6.54653671e-01, -8.91555828e-01],
       [ 9.67114161e-03, -1.26344693e+00,  9.17662935e-01,
        -6.43538199e-01,  1.52752523e+00,  1.12163475e+00],
       [ 9.32825568e-01,  1.38028784e+00, -1.08972474e+00,
        -6.43538199e-01, -6.54653671e-01, -8.91555828e-01],
       [ 2.55845655e-01, -2.73301507e-02,  9.17662935e-01,
        -6.43538199e-01,  1.52752523e+00,  1.12163475e+00],
       [ 1.11745645e+00,  7.20008180e-01,  9.17662935e-01,
        -6.43538199e-01, -6.54653671e-01,  1.12163475e+00],
       [ 9.94369196e-01,  8.95232172e-02,  9.176

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier =RandomForestClassifier(n_estimators=7,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=7, random_state=0)

In [ ]:
y_pred=classifier.predict(x_test)
y_pred

array(['drugX', 'DrugY', 'drugX', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'drugA', 'drugX', 'drugA', 'drugX', 'DrugY', 'drugA',
       'drugB', 'DrugY', 'drugB', 'drugX', 'drugC', 'DrugY', 'drugB',
       'drugX', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugC', 'drugX',
       'DrugY', 'drugX', 'DrugY', 'drugC', 'drugC', 'DrugY', 'drugA',
       'DrugY', 'drugX', 'drugA', 'DrugY', 'drugA', 'drugX', 'drugX',
       'drugX', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'drugX', 'DrugY', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugA', 'DrugY', 'DrugY', 'DrugY'], dtype=object)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[26,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  6,  0],
       [ 0,  0,  0,  0, 18]])

In [ ]:
accuracy_score(y_test,y_pred)

1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=7,criterion='gini',random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9833333333333333